apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: internship
  creationTimestamp: null
  labels:
    name: hafsa
  name: hafsa-internship
spec:
  progressDeadleSeconds: 2147483647
  replicas: 1
  selector:
    matchLabels:
      service: hafsa-internship
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: hafsa-internship
    spec:
      containers:
      - name: hafsa-internship
        image: docker.et3.co/internship.hafsa:latest
        command: ["sh"]
        args: ["runserver.sh"]
        env:
          - name: DEBUG
            value: "False"        
          - name: SQL_USER
            value: postgres
          - name: SQL_ENGINE
            value: django.db.backends.postgresql_psycopg2
          - name: SQL_PASSWORD
            value: postgres
          - name: SQL_HOST
            value: db
          - name: SQL_PORT
            value: "5432"
          - name: SQL_DB
            value: postgres
          - name: MEDIA_ROOT
            value: /usr/src/media
        volumeMounts:
        - mountPath: /usr/src/app/data
          name: hafsa-internship-volume-mount
        - mountPath: /usr/src/media
          name: hafsa-media-internship-volume-mount
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: hafsa-internship-volume-mount
        persistentVolumeClaim:
          claimName: hafsa-internship-pvc
      - name: hafsa-media-internship-volume-mount
        persistentVolumeClaim:
          claimName: hafsa-media-internship-pvc

