apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: internship
  name: Hafsa-internship-pv
  labels:
    type: local
spec:
  capacity:
    storage: 0.1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/Hafsa-internship-pv"
