# Generated by Django 3.2.15 on 2022-09-04 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internshipcash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('amount', models.FloatField(default=0.0)),
                ('transaction_time', models.DateTimeField(verbose_name='date created')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internshipcash.account')),
            ],
        ),
    ]
