# Generated by Django 3.2.15 on 2022-09-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshipcash', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('t', 'Transfer'), ('in', 'Cash in'), ('out', 'Cash out')], max_length=20),
        ),
    ]
