# Generated by Django 3.2.15 on 2022-09-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshipcash', '0003_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiverAccNumber',
            field=models.CharField(default='000000000', max_length=9),
        ),
    ]
