# Generated by Django 3.2.15 on 2022-09-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshipcash', '0004_transaction_receiveraccnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fee',
            field=models.FloatField(default=0.0),
        ),
    ]
