# Generated by Django 3.2.15 on 2022-09-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internshipcash', '0005_transaction_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='fee',
        ),
    ]
