# Generated by Django 3.2.15 on 2022-09-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshipcash', '0007_transaction_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fee',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
