apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: internship
  creationTimestamp: null
  labels:
    name: database
  name: postgres-internship-hafsa
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  selector:
    matchLabels:
      service: postgres-internship-hafsa
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: postgres-internship-hafsa
    spec:
      containers:
        - name: postgres-internship-hafsa
          image: postgres:12.1-alpine
          env:
            - name: POSTGRES_USER
              value: internship
            - name: POSTGRES_PASSWORD
              value: ese123
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-internship-hafsa-volume-mount
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: postgres-internship-hafsa-volume-mount
          persistentVolumeClaim:
            claimName: postgres-internship-hafsa-pvc
