apiVersion: v1
kind: Service
metadata:
  namespace: internship
  name: postgres-internship-hafsa
  labels:
    service: postgres-internship-hafsa
spec:
  selector:
    service: postgres-internship-hafsa
  type: ClusterIP
  ports:
  - port: 5432
